Fix: Resolve TypeScript errors
Fixes the following TypeScript errors:
- src/pages/Projects.tsx(72,30): Cannot find name 'cn'.
- src/pages/Skills.tsx(66,14): Property 'url' does not exist on type '{ name: string; issuer: string; date: string; }'.
- src/pages/Skills.tsx(72,9): Property 'iconSrc' does not exist on type '{ name: string; issuer: string; date: string; }'.
- src/pages/Skills.tsx(74,17): Property 'iconSrc' does not exist on type '{ name: string; issuer: string; date: string; }'.